//
// Created by said2 on 10-11-2022.
//

#ifndef MEATBOY_SAID_YANDARBIEV_CONCRETEFACTORY_H
#define MEATBOY_SAID_YANDARBIEV_CONCRETEFACTORY_H


class ConcreteFactory {

};


#endif //MEATBOY_SAID_YANDARBIEV_CONCRETEFACTORY_H
