//
// Created by said2 on 10-11-2022.
//

#ifndef MEATBOY_SAID_YANDARBIEV_STATEMANAGER_H
#define MEATBOY_SAID_YANDARBIEV_STATEMANAGER_H


class StateManager {

};


#endif //MEATBOY_SAID_YANDARBIEV_STATEMANAGER_H
